---
storage_classes:
  - name: maxiops
    is_default: true
    expand_persistent_volumes: true
    parameters:
      tier: maxiops
  - name: standard
    is_default: false
    expand_persistent_volumes: true
    parameters:
      tier: standard
  # New hdd tier
  - name: archive
    is_default: false
    expand_persistent_volumes: true
    parameters:
      tier: archive
  # tier hdd is deprecated
  - name: hdd
    is_default: false
    expand_persistent_volumes: true
    parameters:
      tier: hdd
  - name: maxiops-encrypted
    is_default: false
    expand_persistent_volumes: true
    parameters:
      tier: maxiops
      encryption: "data-at-rest"
  - name: standard-encrypted
    is_default: false
    expand_persistent_volumes: true
    parameters:
      tier: standard
      encryption: "data-at-rest"
  - name: archive-encrypted
    is_default: false
    expand_persistent_volumes: true
    parameters:
      tier: archive
      encryption: "data-at-rest"
